# Generated by Django 4.2 on 2023-04-27 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_operation_role_studentactivity_roleoperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('region', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professor_id', models.CharField(max_length=10)),
                ('is_science_committee', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('established_year', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=200)),
                ('region', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('title', models.CharField(choices=[('k', 'kar-danesh'), ('f', 'fani'), ('d', 'dabirestan'), ('n', None)], default='n', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=200)),
                ('professor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_to_student', to='accounts.professor')),
                ('school2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_to_student', to='accounts.school')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('field', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('Level_of_education', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExtraUserInfo',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_to_student', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='school',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='office_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_to_school', to='accounts.officemanager'),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher_to_school', to='accounts.teacher'),
        ),
    ]
