# Generated by Django 4.2 on 2023-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_officemanager_professor_school_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
