# Generated by Django 4.1.7 on 2023-05-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_school_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_to_student', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_to_student', to='accounts.teacher'),
        ),
    ]
