# Generated by Django 4.2.3 on 2023-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_student_school2_alter_student_teacher2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
