# Generated by Django 4.2.3 on 2023-07-14 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="office_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_to_school",
                to="accounts.officemanager",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="teacher",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teacher_to_school",
                to="accounts.teacher",
            ),
        ),
    ]
