# Generated by Django 4.2.4 on 2023-08-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_school_manager_alter_school_office_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="professor2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_to_student",
                to="accounts.professor",
            ),
        ),
    ]
