# Generated by Django 4.1.7 on 2023-08-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_professor2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field',
            field=models.CharField(blank=True, default='computer', max_length=200, null=True),
        ),
    ]
