# Generated by Django 4.1.7 on 2023-08-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='office_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_to_school', to='accounts.officemanager'),
            preserve_default=False,
        ),
    ]
