# Generated by Django 4.1.7 on 2023-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_school_manager_alter_school_office_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Level_of_education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
