# Generated by Django 4.1.7 on 2023-08-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teacher_level_of_education_alter_teacher_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentUniqueCode',
        ),
    ]
