# Generated by Django 4.1.7 on 2023-08-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_student_id_student_studentuniquecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='School3',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('established_year', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=200)),
                ('region', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('manager', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('k', 'kar-danesh'), ('f', 'fani'), ('d', 'dabirestan'), ('n', None)], default='n', max_length=100)),
                ('office_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_to_school3', to='accounts.officemanager')),
                ('teacher', models.ManyToManyField(blank=True, null=True, related_name='teacher_to_school3', to='accounts.teacher')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
