# Generated by Django 4.1.7 on 2023-08-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_student_school2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
