# Generated by Django 4.1.7 on 2023-08-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_school_manager'),
        ('accounts', '0018_delete_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School3',
            new_name='School',
        ),
    ]
