# Generated by Django 4.2.4 on 2023-08-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_rename_school3_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="office_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_to_school",
                to="accounts.officemanager",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="teacher",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teacher_to_school",
                to="accounts.teacher",
            ),
        ),
    ]
