# Generated by Django 4.1.7 on 2023-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentUniqueCode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
