# Generated by Django 4.1.7 on 2023-09-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_professor_professor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
