# Generated by Django 4.1.7 on 2023-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_student_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field',
            field=models.CharField(blank=True, default='computer', max_length=200, null=True),
        ),
    ]
