# Generated by Django 4.1.7 on 2023-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_student_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
