# Generated by Django 4.1.7 on 2023-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_officemanager_region_alter_school_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemanager',
            name='region',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
