# Generated by Django 4.1.7 on 2023-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_officemanager_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemanager',
            name='region',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
