# Generated by Django 4.2.5 on 2023-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_officemanager_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_professors',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
