# Generated by Django 4.1.7 on 2023-09-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_alter_student_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_request_professor', to='accounts.professor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_request_student', to='accounts.student')),
            ],
        ),
    ]
