# Generated by Django 4.2.4 on 2023-08-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("request", "0005_delete_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolRequestNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("n", "not sent"),
                            ("s", "Sent"),
                            ("p", "Pending"),
                            ("na", "not accepted"),
                            ("a", "Accepted"),
                        ],
                        default="s",
                        max_length=100,
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        choices=[("s", "seen"), ("u", "unseen")],
                        default="u",
                        max_length=100,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request.request",
                    ),
                ),
            ],
        ),
    ]
