# Generated by Django 4.2.4 on 2023-08-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="schoolrequestnotification", name="status",),
    ]
