# Generated by Django 4.2.4 on 2023-08-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_remove_schoolrequestnotification_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="schoolrequestnotification", name="view",),
    ]
