# Generated by Django 4.1.7 on 2023-09-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_remove_schoolrequestnotification_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrequestnotification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='schoolrequestnotification',
            name='request',
        ),
        migrations.AddField(
            model_name='schoolrequestnotification',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrequestnotification',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notif_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrequestnotification',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolrequestnotification',
            name='view',
            field=models.CharField(choices=[('s', 'seen'), ('u', 'unseen')], default='u', max_length=100),
        ),
    ]
