# Generated by Django 4.1.7 on 2023-09-17 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_remove_schoolrequestnotification_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolRequestNotification',
            new_name='Notification',
        ),
    ]
