# Generated by Django 4.1.7 on 2023-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_rename_schoolrequestnotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
