# Generated by Django 4.2.4 on 2023-08-11 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_alter_school_manager_alter_school_office_manager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200, verbose_name="نام مدرسه"),
                ),
                (
                    "is_present",
                    models.BooleanField(default=False, verbose_name="حاضر ؟"),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date(2023, 8, 11), verbose_name="تاریخ"
                    ),
                ),
                (
                    "enterance_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان ورود به مدرسه"
                    ),
                ),
                (
                    "exit_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان خروج از مدرسه"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "school_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.school",
                        verbose_name="نام مدیر",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                        verbose_name="دانشجو",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teacher",
                        verbose_name="نام معلم",
                    ),
                ),
            ],
        ),
    ]
