# Generated by Django 4.2.4 on 2023-08-11 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاریخ"
            ),
        ),
    ]
