# Generated by Django 4.1.7 on 2023-08-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_school3'),
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='school_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school3', verbose_name='نام مدیر'),
        ),
    ]
