# Generated by Django 4.1.7 on 2023-09-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_school_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='enterance_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='school_manager',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
