# Generated by Django 4.1.7 on 2023-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
