# Generated by Django 4.1.7 on 2023-09-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_school_office_manager_alter_school_teacher'),
        ('attendance', '0006_delete_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance2',
            new_name='Attendance',
        ),
    ]
