# Generated by Django 4.2.5 on 2023-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_rendertask_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='file',
            field=models.FileField(upload_to='tasks/'),
        ),
    ]
