# Generated by Django 4.2.6 on 2023-10-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_rendertask_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
