# Generated by Django 4.1.7 on 2023-08-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
    ]
