# Generated by Django 4.1.7 on 2023-08-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_rename_reciever_request_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('u', 'Unseen'), ('p', 'Pending'), ('n', 'not confirmed'), ('c', 'Connecting')], default='u', max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
