# Generated by Django 4.1.7 on 2023-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('u', 'Unseen'), ('p', 'Pending'), ('s', 'Seen'), ('n', 'not confirmed'), ('c', 'Connecting')], default='u', max_length=100),
        ),
    ]
