# Generated by Django 4.2.4 on 2023-08-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0004_alter_notification_status"),
    ]

    operations = [
        migrations.DeleteModel(name="Notification",),
    ]
