# Generated by Django 4.2.4 on 2023-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0005_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("n", "not sent"),
                    ("s", "Sent"),
                    ("p", "Pending"),
                    ("na", "not accepted"),
                    ("a", "Accepted"),
                ],
                default="s",
                max_length=100,
            ),
        ),
    ]
