# Generated by Django 4.2.4 on 2023-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0006_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="view",
            field=models.CharField(
                choices=[("s", "seen"), ("u", "unseen")], default="u", max_length=100
            ),
        ),
    ]
