# Generated by Django 4.1.7 on 2023-09-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_request_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='view',
        ),
    ]
