# Generated by Django 4.1.7 on 2023-09-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_request_receiver_alter_request_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='body',
            field=models.CharField(default={models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='accounts.student')}, max_length=100),
        ),
    ]
