# Generated by Django 4.1.7 on 2023-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.CharField(max_length=100),
        ),
    ]
