# Generated by Django 4.1.7 on 2023-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_alter_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> sent a request', max_length=100),
        ),
    ]
