# Generated by Django 4.2.5 on 2023-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_alter_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
