# Generated by Django 4.2.5 on 2023-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_alter_request_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
