# Generated by Django 4.1.7 on 2023-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_request_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
