# Generated by Django 4.1.7 on 2023-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_alter_request_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
